/**
 * `storm project remove` — take storm out of a project (typically one that
 * was imported), leaving the user's code exactly as it was.
 *
 * Removed (only if they are storm's):
 *   - project.config.json, TASKS.md, .context-compact/
 *   - CLAUDE.md / AGENTS.md / .opencode/AGENTS.md when generated by storm
 *     (recognized by their storm-ai header); hand-written ones are kept
 *   - storm's built-in commands/roles in .claude/commands and .opencode/
 *   - the fields storm generated in opencode.json / .claude/settings.local.json,
 *     .storm/agent-config.json and storm's .gitignore rules
 *   - directories left empty by the above
 *
 * Kept: any other file, including skill/agent files the user may have
 * filled in (.claude/skills, .claude/agents, custom .opencode/agents).
 */

import { readFile, readdir, rm, rmdir, stat } from 'node:fs/promises';
import path from 'node:path';

import { removeAgentConfig } from '../core/agent-config.js';
import { BUILTIN_OPENCODE_COMMANDS, BUILTIN_OPENCODE_AGENTS } from '../core/opencode-scaffold.js';

const CLAUDE_BUILTIN_COMMANDS = ['task-add', 'task-done', 'task-start', 'refresh-compact'];
const STORM_MD_MARKER = /\*\*storm-ai\*\*/;
const TASKS_MARKER = /storm task/;

/**
 * @typedef {Object} RemovePlan
 * @property {string} projectRoot
 * @property {string[]} remove      Project-relative files/dirs that will be deleted.
 * @property {string[]} keep        Storm-looking files kept because they were edited or are user content.
 * @property {string[]} native      Native CLI config files that get cleaned or deleted.
 */

/**
 * Work out what `removeStorm` would delete, without touching anything.
 * @param {string} projectRoot
 * @returns {Promise<RemovePlan>}
 */
export async function planRemoval(projectRoot) {
  const remove = [];
  const keep = [];
  const has = (rel) => exists(path.join(projectRoot, rel));
  const text = (rel) => readFile(path.join(projectRoot, rel), 'utf8').catch(() => '');

  if (!(await has('project.config.json'))) {
    throw new Error(`${projectRoot} no es un proyecto storm (no tiene project.config.json).`);
  }
  remove.push('project.config.json');
  if (await has('.context-compact')) remove.push('.context-compact/');

  if (await has('TASKS.md')) {
    (TASKS_MARKER.test(await text('TASKS.md')) ? remove : keep).push('TASKS.md');
  }
  for (const rel of ['CLAUDE.md', 'AGENTS.md', '.opencode/AGENTS.md']) {
    if (await has(rel)) (STORM_MD_MARKER.test(await text(rel)) ? remove : keep).push(rel);
  }

  for (const name of CLAUDE_BUILTIN_COMMANDS) {
    const rel = `.claude/commands/${name}.md`;
    if (await has(rel)) ((await text(rel)).startsWith(`# /${name}`) ? remove : keep).push(rel);
  }
  for (const spec of BUILTIN_OPENCODE_COMMANDS) {
    const rel = `.opencode/commands/${spec.id}.md`;
    if (await has(rel)) (/storm/i.test(await text(rel)) ? remove : keep).push(rel);
  }
  for (const spec of BUILTIN_OPENCODE_AGENTS) {
    const rel = `.opencode/agents/${spec.id}.md`;
    if (await has(rel)) (/storm/i.test(await text(rel)) ? remove : keep).push(rel);
  }

  const native = await removeAgentConfig(projectRoot, { dryRun: true });
  return {
    projectRoot,
    remove,
    keep,
    native: [...native.deletedFiles.map((f) => `${f} (borrar)`), ...native.changedFiles.map((f) => `${f} (limpiar campos de storm)`)],
  };
}

/**
 * Remove storm from a project.
 * @param {string} projectRoot
 * @returns {Promise<RemovePlan & {removedDirs: string[]}>}
 */
export async function removeStorm(projectRoot) {
  const plan = await planRemoval(projectRoot);
  // Native config first: it reads project files that are about to go.
  await removeAgentConfig(projectRoot);
  for (const rel of plan.remove) {
    await rm(path.join(projectRoot, rel), { recursive: true, force: true });
  }
  const removedDirs = [];
  for (const dir of ['.claude/commands', '.claude/skills', '.claude/agents', '.claude',
    '.opencode/commands', '.opencode/agents', '.opencode', '.storm']) {
    if (await removeIfEmpty(path.join(projectRoot, dir))) removedDirs.push(`${dir}/`);
  }
  return { ...plan, removedDirs };
}

async function removeIfEmpty(dir) {
  try {
    if ((await readdir(dir)).length > 0) return false;
    await rmdir(dir);
    return true;
  } catch {
    return false;
  }
}

async function exists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}
