/**
 * Task CRUD over task-state.json.
 *
 * Single source of truth for task data. TASKS.md is a VIEW generated from
 * this file — never edited directly.
 *
 * Design decisions:
 *   - IDs are sequential ("T-001", "T-002"...). Sequential IDs are easier
 *     to reference verbally than UUIDs ("finish T-003" vs "finish a8f3..").
 *   - `branches` on each task is validated against project.config.json at
 *     write time, so typos ("src/autth") fail fast.
 *   - Reading is cheap and called often; writing normalizes + validates.
 *   - All public functions take `projectRoot` and read/write fresh — no
 *     in-memory cache — because the user may edit files externally and
 *     we must not overwrite their changes with stale data.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

/** @typedef {'pending'|'in_progress'|'done'|'cancelled'} TaskStatus */

/**
 * @typedef {Object} Task
 * @property {string} id
 * @property {string} title
 * @property {string} description
 * @property {TaskStatus} status
 * @property {string[]} branches          Paths into branches_index.
 * @property {string} created_at          ISO 8601.
 * @property {string} updated_at          ISO 8601.
 * @property {string|null} completed_at   ISO 8601 or null.
 * @property {Array<{at: string, content: string}>} notes
 */

/**
 * @typedef {Object} TaskState
 * @property {number} version
 * @property {{name: string, created_at: string}} project
 * @property {{done_since_refresh: number, auto_refresh_threshold: number, last_refresh_at: string|null}} counters
 * @property {string[]} branches_index
 * @property {Task[]} tasks
 */

export const VALID_STATUSES = ['pending', 'in_progress', 'done', 'cancelled'];
const STATE_FILE = path.join('.context-compact', 'task-state.json');
const TASKS_FILE = 'TASKS.md';
const DEFAULT_THRESHOLD = 5;

// ---------------------------------------------------------------------------
// I/O helpers
// ---------------------------------------------------------------------------

/**
 * @param {string} projectRoot
 * @returns {Promise<TaskState>}
 */
export async function readState(projectRoot) {
  const p = path.join(projectRoot, STATE_FILE);
  let raw;
  try {
    raw = await readFile(p, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      throw new TaskStateError(
        `No task-state.json at ${p}. Is this a storm project? Run 'storm new' first.`,
      );
    }
    throw err;
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new TaskStateError(`task-state.json is not valid JSON: ${err.message}`);
  }

  return normalizeState(parsed);
}

/**
 * @param {string} projectRoot
 * @param {TaskState} state
 */
export async function writeState(projectRoot, state) {
  const p = path.join(projectRoot, STATE_FILE);
  await mkdir(path.dirname(p), { recursive: true });
  // UTF-8 WITHOUT BOM — node writeFile default already does this.
  await writeFile(p, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

/**
 * Regenerate TASKS.md from the authoritative state.
 * Called after every mutation.
 *
 * @param {string} projectRoot
 * @param {TaskState} state
 */
export async function regenerateTasksMd(projectRoot, state) {
  const byStatus = {
    in_progress: state.tasks.filter((t) => t.status === 'in_progress'),
    pending: state.tasks.filter((t) => t.status === 'pending'),
    done: state.tasks.filter((t) => t.status === 'done'),
    cancelled: state.tasks.filter((t) => t.status === 'cancelled'),
  };

  const fmtLine = (t) => {
    const branches = t.branches.length ? ` _[${t.branches.join(', ')}]_` : '';
    return `- **${t.id}** ${t.title}${branches}`;
  };

  const sections = [
    '# Tasks',
    '',
    `_Last updated: ${new Date().toISOString()}_`,
    `_Auto-source: \`.context-compact/task-state.json\`. Do not edit this file directly — use \`storm task\` commands._`,
    '',
    '## In progress',
    byStatus.in_progress.length ? byStatus.in_progress.map(fmtLine).join('\n') : '_None_',
    '',
    '## Pending',
    byStatus.pending.length ? byStatus.pending.map(fmtLine).join('\n') : '_None_',
    '',
    '## Done',
    byStatus.done.length ? byStatus.done.map(fmtLine).join('\n') : '_None_',
    '',
    '## Cancelled',
    byStatus.cancelled.length ? byStatus.cancelled.map(fmtLine).join('\n') : '_None_',
    '',
  ];

  await writeFile(path.join(projectRoot, TASKS_FILE), sections.join('\n'), 'utf8');
}

// ---------------------------------------------------------------------------
// CRUD
// ---------------------------------------------------------------------------

/**
 * @param {string} projectRoot
 * @param {{title: string, description?: string, branches?: string[]}} input
 * @returns {Promise<Task>}
 */
export async function addTask(projectRoot, input) {
  const state = await readState(projectRoot);

  if (!input.title?.trim()) {
    throw new TaskStateError('Task title is required.');
  }
  const branches = input.branches ?? [];
  assertBranchesValid(branches, state.branches_index);

  const id = nextId(state.tasks);
  const now = new Date().toISOString();
  /** @type {Task} */
  const task = {
    id,
    title: input.title.trim(),
    description: (input.description ?? '').trim(),
    status: 'pending',
    branches: [...branches],
    created_at: now,
    updated_at: now,
    completed_at: null,
    notes: [],
  };

  state.tasks.push(task);
  await writeState(projectRoot, state);
  await regenerateTasksMd(projectRoot, state);
  return task;
}

/**
 * @param {string} projectRoot
 * @param {string} id
 * @param {TaskStatus} newStatus
 * @returns {Promise<{task: Task, shouldRefresh: boolean}>}
 */
export async function setStatus(projectRoot, id, newStatus) {
  if (!VALID_STATUSES.includes(newStatus)) {
    throw new TaskStateError(
      `Invalid status '${newStatus}'. Valid: ${VALID_STATUSES.join(', ')}.`,
    );
  }

  const state = await readState(projectRoot);
  const task = state.tasks.find((t) => t.id === id);
  if (!task) throw new TaskStateError(`Task ${id} not found.`);

  const wasDone = task.status === 'done';
  const nowDone = newStatus === 'done';

  task.status = newStatus;
  task.updated_at = new Date().toISOString();
  task.completed_at = nowDone ? task.updated_at : null;

  // Counter logic: only increment when we TRANSITION into done.
  let shouldRefresh = false;
  if (!wasDone && nowDone) {
    state.counters.done_since_refresh += 1;
    if (state.counters.done_since_refresh >= state.counters.auto_refresh_threshold) {
      shouldRefresh = true;
      // Note: we don't reset the counter here — that's the refresh command's
      // job, after it successfully regenerates compact files. If the refresh
      // fails, the counter stays high and the user gets prompted again.
    }
  }

  await writeState(projectRoot, state);
  await regenerateTasksMd(projectRoot, state);
  return { task, shouldRefresh };
}

/**
 * @param {string} projectRoot
 * @param {string} id
 * @param {string} content
 */
export async function addNote(projectRoot, id, content) {
  const state = await readState(projectRoot);
  const task = state.tasks.find((t) => t.id === id);
  if (!task) throw new TaskStateError(`Task ${id} not found.`);
  task.notes.push({ at: new Date().toISOString(), content: content.trim() });
  task.updated_at = new Date().toISOString();
  await writeState(projectRoot, state);
}

/**
 * Called by the refresh command after compact files were regenerated
 * successfully. Resets the counter atomically.
 *
 * @param {string} projectRoot
 */
export async function markRefreshed(projectRoot) {
  const state = await readState(projectRoot);
  state.counters.done_since_refresh = 0;
  state.counters.last_refresh_at = new Date().toISOString();
  await writeState(projectRoot, state);
}

/**
 * @param {string} projectRoot
 * @param {{status?: TaskStatus, branch?: string}} [filter]
 */
export async function listTasks(projectRoot, filter = {}) {
  const state = await readState(projectRoot);
  let tasks = state.tasks;
  if (filter.status) tasks = tasks.filter((t) => t.status === filter.status);
  if (filter.branch) tasks = tasks.filter((t) => t.branches.includes(filter.branch));
  return tasks;
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

export class TaskStateError extends Error {
  constructor(message) {
    super(message);
    this.name = 'TaskStateError';
  }
}

/**
 * Ensure the state object has all expected fields with reasonable defaults.
 * Called on every read; makes older state files forward-compatible.
 *
 * @param {any} raw
 * @returns {TaskState}
 */
function normalizeState(raw) {
  const state = raw ?? {};
  state.version ??= 1;
  state.project ??= { name: 'unknown', created_at: new Date().toISOString() };
  state.counters ??= {};
  state.counters.done_since_refresh ??= 0;
  state.counters.auto_refresh_threshold ??= DEFAULT_THRESHOLD;
  state.counters.last_refresh_at ??= null;
  state.branches_index ??= [];
  state.tasks ??= [];

  for (const t of state.tasks) {
    t.branches ??= [];
    t.notes ??= [];
    t.completed_at ??= null;
    t.description ??= '';
  }

  return state;
}

/**
 * @param {Task[]} tasks
 * @returns {string} Next sequential ID, e.g. "T-017".
 */
function nextId(tasks) {
  let max = 0;
  for (const t of tasks) {
    const m = /^T-(\d+)$/.exec(t.id);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  return `T-${String(max + 1).padStart(3, '0')}`;
}

/**
 * @param {string[]} wanted
 * @param {string[]} index
 */
function assertBranchesValid(wanted, index) {
  if (wanted.length === 0) return;
  if (index.length === 0) return; // empty index = don't validate (fresh project)
  const bad = wanted.filter((b) => !index.includes(b));
  if (bad.length > 0) {
    throw new TaskStateError(
      `Unknown branch(es): ${bad.join(', ')}. Known branches: ${index.join(', ')}.`,
    );
  }
}
