/**
 * Regenerate src/assets/logo-pixels.js from assets/logo.png.
 *
 *   npm run build:logo
 *
 * The CLI draws the logo from those precomputed pixels, so `sharp` (a
 * heavy native dependency) is only needed here, as a devDependency, and
 * never installed for users.
 *
 * Steps: auto-crop the black borders, resize to COLS × (rows*2) pixels
 * (two source rows per terminal row, drawn with '▀'), store raw RGB.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(root, 'assets/logo.png');
const OUT = path.join(root, 'src/assets/logo-pixels.js');
const COLS = 80;
const CROP_THRESHOLD = 90;

const buf = readFileSync(SRC);
const meta = await sharp(buf).metadata();
const raw = await sharp(buf).removeAlpha().raw().toBuffer();

const bright = (x, y) => {
  const i = (y * meta.width + x) * 3;
  return raw[i] + raw[i + 1] + raw[i + 2];
};
const rowHas = (y) => { for (let x = 0; x < meta.width; x++) if (bright(x, y) > CROP_THRESHOLD) return true; return false; };
const colHas = (x) => { for (let y = 0; y < meta.height; y++) if (bright(x, y) > CROP_THRESHOLD) return true; return false; };
let top = 0; while (top < meta.height && !rowHas(top)) top++;
let bottom = meta.height; while (bottom > top && !rowHas(bottom - 1)) bottom--;
let left = 0; while (left < meta.width && !colHas(left)) left++;
let right = meta.width; while (right > left && !colHas(right - 1)) right--;

const cropW = right - left;
const cropH = bottom - top;
const rows = Math.max(1, Math.round((COLS * (cropH / cropW)) / 2));
const pixels = await sharp(buf)
  .removeAlpha()
  .extract({ left, top, width: cropW, height: cropH })
  .resize(COLS, rows * 2, { fit: 'fill', kernel: 'lanczos3' })
  .raw()
  .toBuffer();

writeFileSync(OUT, `// Generated by scripts/build-logo.mjs from assets/logo.png — do not edit.
// Raw RGB, ${COLS}×${rows * 2} px (two pixel rows per terminal row).
export const LOGO_COLS = ${COLS};
export const LOGO_PIXEL_ROWS = ${rows * 2};
export const LOGO_RGB_BASE64 =
  '${pixels.toString('base64')}';
`);
console.log(`wrote ${path.relative(root, OUT)} (${COLS}x${rows * 2}, ${pixels.length} bytes)`);
